# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

[pytest]
testpaths = tests
python_files = test_*.py
python_functions = test_*
addopts = -ra -q
